name: Rebuild and publish OCI

on:
  push:
    paths: ['src/**', '.github/workflows/publish-oci']

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile
          # ppa*.rabbitmq.com only provide amd64 packages at the moment.
          # Launchpad does produce arm64 packages but cannot be used on Debian :/
          platforms: linux/amd64
          push: true
          tags: rabbitmqdevenv/delete-release-action:latest
